{
  "hash": "541c777993867d32bdc1bbd44392cbf3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 1: Census Data Quality for Policy Decisions\"\nsubtitle: \"Evaluating Data Reliability for Algorithmic Decision-Making\"\nauthor: \"Xiaoqing(Kelsey) Chen\"\ndate: \"2025-09-27\"\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\nexecute:\n  warning: false\n  message: false\n---\n\n# Part 1: Portfolio Integration\n\n```\n- text: Assignments\n  menu:\n    - href: assignments/assignment_1/your_file_name.qmd\n      text: \"Assignment 1: Census Data Exploration\"\n```\n# Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidycensus)\nlibrary(tidyverse)\nlibrary(knitr)\n\ncensus_api_key(\"e17c1c6ce413dc3faca31a17a58ab3374404bb9e\")\n```\n:::\n\n\n**State Selection:** I have chosen **[New York]** for this analysis because: [I travelled to New York this month, so i'm curious about this county.]\n\n# Part 2: County-Level Resource Assessment\n\n## 2.1 Data Retrieval\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstate_pop <- get_acs(\n  geography = \"county\",\n  variables = \"B01003_001\",  \n  state = \"NY\", \n  year = 2022,\n  survey = \"acs5\"\n)\nglimpse(state_pop)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 62\nColumns: 5\n$ GEOID    <chr> \"36001\", \"36003\", \"36005\", \"36007\", \"36009\", \"36011\", \"36013\"…\n$ NAME     <chr> \"Albany County, New York\", \"Allegany County, New York\", \"Bron…\n$ variable <chr> \"B01003_001\", \"B01003_001\", \"B01003_001\", \"B01003_001\", \"B010…\n$ estimate <dbl> 315041, 47222, 1443229, 198365, 77000, 76171, 127440, 83584, …\n$ moe      <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…\n```\n\n\n:::\n\n```{.r .cell-code}\nny_data <- get_acs(\n  geography = \"county\",\n  variables = c(\n    total_pop = \"B01003_001\",\n    median_income = \"B19013_001\"\n  ),\n  state = \"NY\",\n  year = 2022,\n  output = \"wide\"\n)\n\nhead(ny_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  GEOID NAME                 total_popE total_popM median_incomeE median_incomeM\n  <chr> <chr>                     <dbl>      <dbl>          <dbl>          <dbl>\n1 36001 Albany County, New …     315041         NA          78829           2049\n2 36003 Allegany County, Ne…      47222         NA          58725           1965\n3 36005 Bronx County, New Y…    1443229         NA          47036            890\n4 36007 Broome County, New …     198365         NA          58317           1761\n5 36009 Cattaraugus County,…      77000         NA          56889           1778\n6 36011 Cayuga County, New …      76171         NA          63227           2736\n```\n\n\n:::\n\n```{.r .cell-code}\nny_clean <- ny_data %>%\n  mutate(\n    county_name = str_remove(NAME, \", New York\"),\n    county_name = str_remove(county_name, \" County\")\n  )\n```\n:::\n\n\n## 2.2 Data Quality Assessment\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselect(ny_clean, NAME, county_name)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 62 × 2\n   NAME                         county_name\n   <chr>                        <chr>      \n 1 Albany County, New York      Albany     \n 2 Allegany County, New York    Allegany   \n 3 Bronx County, New York       Bronx      \n 4 Broome County, New York      Broome     \n 5 Cattaraugus County, New York Cattaraugus\n 6 Cayuga County, New York      Cayuga     \n 7 Chautauqua County, New York  Chautauqua \n 8 Chemung County, New York     Chemung    \n 9 Chenango County, New York    Chenango   \n10 Clinton County, New York     Clinton    \n# ℹ 52 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\nny_reliability <- ny_clean %>%\n  mutate(\n    moe_percentage = round((median_incomeM / median_incomeE) * 100, 2),\n\n    reliability = case_when(\n      moe_percentage < 5 ~ \"High Confidence\",\n      moe_percentage >= 5 & moe_percentage <= 10 ~ \"Moderate\",\n      moe_percentage > 10 ~ \"Low Confidence\"\n    )\n  )\n\ncount(ny_reliability, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  reliability         n\n  <chr>           <int>\n1 High Confidence    56\n2 Low Confidence      1\n3 Moderate            5\n```\n\n\n:::\n:::\n\n\n## 2.3 High Uncertainty Counties\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhigh_uncertainty <- ny_reliability %>%\n  filter(moe_percentage > 8) %>%\n  arrange(desc(moe_percentage)) %>%\n  select(county_name, median_incomeE, moe_percentage)\n\nreliability_summary <- ny_reliability %>%\n  group_by(reliability) %>%\n  summarize(\n    counties = n(),\n    avg_income = round(mean(median_incomeE, na.rm = TRUE), 0)\n  )\n\nkable(high_uncertainty,\n      col.names = c(\"County\", \"Median Income\", \"MOE %\"),\n      caption = \"Counties with Highest Income Data Uncertainty\",\n      format.args = list(big.mark = \",\"))\n```\n\n::: {.cell-output-display}\n\n\nTable: Counties with Highest Income Data Uncertainty\n\n|County   | Median Income| MOE %|\n|:--------|-------------:|-----:|\n|Hamilton |        66,891| 11.39|\n|Schuyler |        61,316|  9.49|\n\n\n:::\n:::\n\n\n**Data Quality Commentary:**\n\n  [The tables show that counties like Hamilton and Schuyler have high MOE in the income data, which means these data may lead to less reliable outcome or decision for residents in terms of algorithms. Small size of populations and limited survey samples may contribute to this uncertainty, so that unfair treatment or lows may be established which will affect local people in these areas.]\n\n# Part 3: Neighborhood-Level Analysis\n\n## 3.1 Focus Area Selection\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselected_counties <- ny_reliability %>%\n  filter(\n    county_name %in% c(\"Albany\", \"Schuyler\", \"Hamilton\")\n  )\nselected_counties %>%\n  select(county_name, median_incomeE, moe_percentage, reliability)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  county_name median_incomeE moe_percentage reliability    \n  <chr>                <dbl>          <dbl> <chr>          \n1 Albany               78829           2.6  High Confidence\n2 Hamilton             66891          11.4  Low Confidence \n3 Schuyler             61316           9.49 Moderate       \n```\n\n\n:::\n:::\n\n\n**Comment on the output:** [These three countries reflects different levels of reliability. Albany has highly reliable income data with a very low MOE, while Hamilton's data displays higher uncertainty. As a result, lower populations and limited sample sizes may influence the data confidence, which could lead to less stable estimates and algorithmic decisions.]\n\n## 3.2 Tract-Level Demographics\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselected_counties <- c(\"Albany\", \"Hamilton\", \"Schuyler\")\n\nny_lookup <- tidycensus::fips_codes %>%\n  filter(state == \"NY\", county %in% paste0(selected_counties, \" County\")) %>%\n  distinct(county_code, county) %>%\n  mutate(county_name = str_remove(county, \" County\")) %>%\n  select(county_code, county_name)\n\nrace_tract <- get_acs(\n  geography = \"tract\",\n  variables = c(\n    white     = \"B03002_003\",\n    black     = \"B03002_004\",\n    hispanic  = \"B03002_012\",\n    total_pop = \"B03002_001\"\n  ),\n  state  = \"NY\",\n  county = ny_lookup$county_code, \n  year   = 2022,\n  survey = \"acs5\",\n  output = \"wide\"\n)\n\nrace_tract <- race_tract %>%\n  mutate(\n    white_pct    = if_else(total_popE > 0, whiteE    / total_popE, NA_real_),\n    black_pct    = if_else(total_popE > 0, blackE    / total_popE, NA_real_),\n    hispanic_pct = if_else(total_popE > 0, hispanicE / total_popE, NA_real_)\n  )\n\nrace_tract <- race_tract %>%\n  mutate(\n    county_fips = str_sub(GEOID, 3, 5),\n    tract_id    = str_sub(GEOID, 6)\n  ) %>%\n  left_join(ny_lookup, by = c(\"county_fips\" = \"county_code\")) %>%\n  mutate(\n    tract_label = paste0(county_name, \" County – Tract \", tract_id)\n  )\n\nrace_tract %>%\n  select(GEOID, tract_label, county_name,\n         total_popE, whiteE, blackE, hispanicE,\n         white_pct, black_pct, hispanic_pct) %>%\n  arrange(county_name, tract_label) %>%\n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 10\n  GEOID     tract_label county_name total_popE whiteE blackE hispanicE white_pct\n  <chr>     <chr>       <chr>            <dbl>  <dbl>  <dbl>     <dbl>     <dbl>\n1 36001000… Albany Cou… Albany            2259    725    982       346     0.321\n2 36001000… Albany Cou… Albany            2465    372   1742       174     0.151\n3 36001000… Albany Cou… Albany            2374    317   1952        45     0.134\n4 36001000… Albany Cou… Albany            2837    678   1271       673     0.239\n5 36001000… Albany Cou… Albany            3200   1963    538       183     0.613\n6 36001000… Albany Cou… Albany            2301   2012    134        98     0.874\n# ℹ 2 more variables: black_pct <dbl>, hispanic_pct <dbl>\n```\n\n\n:::\n:::\n\n\n## 3.3 Demographic Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_hispanic <- race_tract %>%\n  arrange(desc(hispanic_pct)) %>%\n  slice(1)\n\ntop_hispanic\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 17\n  GEOID       NAME    whiteE whiteM blackE blackM hispanicE hispanicM total_popE\n  <chr>       <chr>    <dbl>  <dbl>  <dbl>  <dbl>     <dbl>     <dbl>      <dbl>\n1 36001002000 Census…   2846    835   1460    445      1562       811       6576\n# ℹ 8 more variables: total_popM <dbl>, white_pct <dbl>, black_pct <dbl>,\n#   hispanic_pct <dbl>, county_fips <chr>, tract_id <chr>, county_name <chr>,\n#   tract_label <chr>\n```\n\n\n:::\n\n```{.r .cell-code}\ncounty_summary <- race_tract %>%\n  group_by(county_name) %>%\n  summarize(\n    n_tracts = n(),\n    avg_white_pct = mean(white_pct, na.rm = TRUE),\n    avg_black_pct = mean(black_pct, na.rm = TRUE),\n    avg_hispanic_pct = mean(hispanic_pct, na.rm = TRUE),\n  )\n\n\ncounty_summary <- race_tract %>%\n  kable(digits = 2, captison = \"Average Demographics by county (Albany, Hamilton, Schuyler)\")\n```\n:::\n\n\n# Part 4: Comprehensive Data Quality Evaluation\n\n## 4.1 MOE Analysis for Demographic Variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndemographic_moe <- race_tract %>%\n  mutate(\n    white_moe_pct    = if_else(is.na(whiteE)    | whiteE    == 0, NA_real_, 100 * whiteM    / whiteE),\n    black_moe_pct    = if_else(is.na(blackE)    | blackE    == 0, NA_real_, 100 * blackM    / blackE),\n    hispanic_moe_pct = if_else(is.na(hispanicE) | hispanicE == 0, NA_real_, 100 * hispanicM / hispanicE)\n  ) \n\ndemographic_moe <- demographic_moe %>%\n  mutate(\n    high_moe_flag = if_else(\n      white_moe_pct > 10 | black_moe_pct > 10 | hispanic_moe_pct > 10,\n      TRUE, FALSE\n    )\n  )\n\nsummary_tracts <- demographic_moe %>%\n  summarise(\n    total_tracts    = n(),\n    high_moe_tracts = sum(high_moe_flag, na.rm = TRUE),\n    pct_high_moe    = 100 * mean(high_moe_flag, na.rm = TRUE)\n  )\nsummary_tracts\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  total_tracts high_moe_tracts pct_high_moe\n         <int>           <int>        <dbl>\n1           94              94          100\n```\n\n\n:::\n:::\n\n\n## 4.2 Pattern Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\navg_characteristics <- demographic_moe %>%\n  group_by(high_moe_flag) %>%\n  summarise(\n    avg_pop      = mean(total_popE, na.rm = TRUE),\n    avg_white    = mean(white_pct, na.rm = TRUE),\n    avg_black    = mean(black_pct, na.rm = TRUE),\n    avg_hispanic = mean(hispanic_pct, na.rm = TRUE),\n    n_tracts     = n()\n  )\n\navg_characteristics\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 6\n  high_moe_flag avg_pop avg_white avg_black avg_hispanic n_tracts\n  <lgl>           <dbl>     <dbl>     <dbl>        <dbl>    <int>\n1 TRUE            3596.     0.711     0.116       0.0607       94\n```\n\n\n:::\n:::\n\n\n**Pattern Analysis:** [Small tract populations would lead to a high MOE, so the related estimated are less reliable. On average, tracts flagged as high MOE only have nearly 3600 people, with minority groups like Hispanics accounting for only 6% of the total population.]\n\n\n# Part 5: Policy Recommendations\n\n## 5.1 Analysis Integration and Professional Summary\n\n**Executive Summary Requirements:**\n1. **Overall Pattern Identification**: What are the systematic patterns across all your analyses?\n2. **Equity Assessment**: Which communities face the greatest risk of algorithmic bias based on your findings?\n3. **Root Cause Analysis**: What underlying factors drive both data quality issues and bias risk?\n4. **Strategic Recommendations**: What should the Department implement to address these systematic issues?\n\n**Executive Summary:**\n\n[All 94 census tracts show at least one demographic group with MOE above 10%, indicating data reliability issues are widespread.For example, Albany County Tract 000100 has White MOE = 46.97%, Black MOE = 36.86%, and Hispanic MOE = 62.71%.\nHispanic populations consistently show the highest MOEs, suggesting this group faces the greatest data reliability challenges.In many tracts, Hispanic MOEs exceed 60% or even 100%, while White and Black MOEs are also high but relatively lower.\nHigh MOE levels are largely driven by small population sizes in many tracts, which make reliable estimates difficult.On average, tracts flagged as high MOE have only about 3,596 people, with Hispanic populations averaging just 6%.\nImproving reliability requires either aggregating data or using multi-year ACS estimates to reduce sampling error.For example, combining smaller tracts or applying a population threshold before analysis would help minimize bias in Hispanic estimates.]\n\n## 6.3 Specific Recommendations\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(kableExtra)\nlibrary(knitr)\n\nkbl_safe <- function(x, ...) {\n  tbl <- knitr::kable(x, ...)\n  if (use_kableExtra) {\n    tbl <- tbl %>% kableExtra::kable_styling(\n      full_width = FALSE,\n      bootstrap_options = c(\"striped\",\"condensed\")\n    )\n  }\n  tbl\n}\n\nmoe_pct <- function(margin, estimate) {\n  ifelse(is.na(estimate) | estimate == 0, NA_real_, 100 * margin / estimate)\n}\n\nrecommendations_data <- ny_reliability %>%\n  mutate(\n    income_moe_pct = if_else(is.na(median_incomeE) | median_incomeE == 0,\n                          NA_real_, 100 * median_incomeM / median_incomeE),\n\n  reliability_category = case_when(\n      !is.na(income_moe_pct) & income_moe_pct <= 5   ~ \"High Confidence\",\n      !is.na(income_moe_pct) & income_moe_pct <= 10  ~ \"Moderate Confidence\",\n      TRUE                                     ~ \"Low Confidence\"\n    ),\n  recommendation = case_when(\n      reliability_category == \"High Confidence\"     ~ \"Safe for algorithmic decisions\",\n      reliability_category == \"Moderate Confidence\" ~ \"Use with caution – monitor outcomes\",\n      reliability_category == \"Low Confidence\"      ~ \"Requires manual review or additional data\"\n    )\n  ) %>%\n  transmute(\n    county_name,\n    median_income = median_incomeE,\n    income_moe_pct = round(income_moe_pct, 1),\n    reliability_category,\n    recommendation\n  )\n\nkable(recommendations_data,\n      col.names = c(\"County\",\"Median Income ($)\",\"Income MOE %\",\"Reliability\",\"Recommendation\"),\n      caption = \"Decision Framework for Algorithmic Implementation\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Decision Framework for Algorithmic Implementation\n\n|County       | Median Income ($)| Income MOE %|Reliability         |Recommendation                            |\n|:------------|-----------------:|------------:|:-------------------|:-----------------------------------------|\n|Albany       |             78829|          2.6|High Confidence     |Safe for algorithmic decisions            |\n|Allegany     |             58725|          3.3|High Confidence     |Safe for algorithmic decisions            |\n|Bronx        |             47036|          1.9|High Confidence     |Safe for algorithmic decisions            |\n|Broome       |             58317|          3.0|High Confidence     |Safe for algorithmic decisions            |\n|Cattaraugus  |             56889|          3.1|High Confidence     |Safe for algorithmic decisions            |\n|Cayuga       |             63227|          4.3|High Confidence     |Safe for algorithmic decisions            |\n|Chautauqua   |             54625|          3.2|High Confidence     |Safe for algorithmic decisions            |\n|Chemung      |             61358|          4.0|High Confidence     |Safe for algorithmic decisions            |\n|Chenango     |             61741|          4.1|High Confidence     |Safe for algorithmic decisions            |\n|Clinton      |             67097|          4.2|High Confidence     |Safe for algorithmic decisions            |\n|Columbia     |             81741|          3.4|High Confidence     |Safe for algorithmic decisions            |\n|Cortland     |             65029|          4.4|High Confidence     |Safe for algorithmic decisions            |\n|Delaware     |             58338|          3.7|High Confidence     |Safe for algorithmic decisions            |\n|Dutchess     |             94578|          2.7|High Confidence     |Safe for algorithmic decisions            |\n|Erie         |             68014|          1.2|High Confidence     |Safe for algorithmic decisions            |\n|Essex        |             68090|          5.3|Moderate Confidence |Use with caution – monitor outcomes       |\n|Franklin     |             60270|          4.8|High Confidence     |Safe for algorithmic decisions            |\n|Fulton       |             60557|          4.4|High Confidence     |Safe for algorithmic decisions            |\n|Genesee      |             68178|          4.6|High Confidence     |Safe for algorithmic decisions            |\n|Greene       |             70294|          6.2|Moderate Confidence |Use with caution – monitor outcomes       |\n|Hamilton     |             66891|         11.4|Low Confidence      |Requires manual review or additional data |\n|Herkimer     |             68104|          4.8|High Confidence     |Safe for algorithmic decisions            |\n|Jefferson    |             62782|          3.6|High Confidence     |Safe for algorithmic decisions            |\n|Kings        |             74692|          1.3|High Confidence     |Safe for algorithmic decisions            |\n|Lewis        |             64401|          4.2|High Confidence     |Safe for algorithmic decisions            |\n|Livingston   |             70443|          4.0|High Confidence     |Safe for algorithmic decisions            |\n|Madison      |             68869|          4.0|High Confidence     |Safe for algorithmic decisions            |\n|Monroe       |             71450|          1.4|High Confidence     |Safe for algorithmic decisions            |\n|Montgomery   |             58033|          3.6|High Confidence     |Safe for algorithmic decisions            |\n|Nassau       |            137709|          1.4|High Confidence     |Safe for algorithmic decisions            |\n|New York     |             99880|          1.8|High Confidence     |Safe for algorithmic decisions            |\n|Niagara      |             65882|          2.7|High Confidence     |Safe for algorithmic decisions            |\n|Oneida       |             66402|          3.3|High Confidence     |Safe for algorithmic decisions            |\n|Onondaga     |             71479|          1.6|High Confidence     |Safe for algorithmic decisions            |\n|Ontario      |             76603|          2.9|High Confidence     |Safe for algorithmic decisions            |\n|Orange       |             91806|          1.9|High Confidence     |Safe for algorithmic decisions            |\n|Orleans      |             61069|          4.9|High Confidence     |Safe for algorithmic decisions            |\n|Oswego       |             65054|          3.3|High Confidence     |Safe for algorithmic decisions            |\n|Otsego       |             65778|          4.5|High Confidence     |Safe for algorithmic decisions            |\n|Putnam       |            120970|          4.0|High Confidence     |Safe for algorithmic decisions            |\n|Queens       |             82431|          1.1|High Confidence     |Safe for algorithmic decisions            |\n|Rensselaer   |             83734|          2.3|High Confidence     |Safe for algorithmic decisions            |\n|Richmond     |             96185|          2.6|High Confidence     |Safe for algorithmic decisions            |\n|Rockland     |            106173|          2.9|High Confidence     |Safe for algorithmic decisions            |\n|St. Lawrence |             58339|          3.5|High Confidence     |Safe for algorithmic decisions            |\n|Saratoga     |             97038|          2.3|High Confidence     |Safe for algorithmic decisions            |\n|Schenectady  |             75056|          3.0|High Confidence     |Safe for algorithmic decisions            |\n|Schoharie    |             71479|          4.0|High Confidence     |Safe for algorithmic decisions            |\n|Schuyler     |             61316|          9.5|Moderate Confidence |Use with caution – monitor outcomes       |\n|Seneca       |             64050|          5.2|Moderate Confidence |Use with caution – monitor outcomes       |\n|Steuben      |             62506|          2.9|High Confidence     |Safe for algorithmic decisions            |\n|Suffolk      |            122498|          1.2|High Confidence     |Safe for algorithmic decisions            |\n|Sullivan     |             67841|          4.4|High Confidence     |Safe for algorithmic decisions            |\n|Tioga        |             70427|          4.0|High Confidence     |Safe for algorithmic decisions            |\n|Tompkins     |             69995|          4.0|High Confidence     |Safe for algorithmic decisions            |\n|Ulster       |             77197|          4.5|High Confidence     |Safe for algorithmic decisions            |\n|Warren       |             74531|          4.7|High Confidence     |Safe for algorithmic decisions            |\n|Washington   |             68703|          3.4|High Confidence     |Safe for algorithmic decisions            |\n|Wayne        |             71007|          3.1|High Confidence     |Safe for algorithmic decisions            |\n|Westchester  |            114651|          1.6|High Confidence     |Safe for algorithmic decisions            |\n|Wyoming      |             65066|          3.4|High Confidence     |Safe for algorithmic decisions            |\n|Yates        |             63974|          5.8|Moderate Confidence |Use with caution – monitor outcomes       |\n\n\n:::\n:::\n\n\nrecommendations_data %>% filter(reliability_category == \"High Confidence\")\nrecommendations_data %>% filter(reliability_category == \"Moderate Confidence\")\nrecommendations_data %>% filter(reliability_category == \"Low Confidence\")\n\n1. **Counties suitable for immediate algorithmic implementation:** [All counties with MOE below 5% can be safely used for automated decisions. For example, Albany, Allegany, and Bronx all show income MOE between 3–4%, indicating strong reliability. Other counties of high confidence inculdes Broome, Cattaraugus, Cayuge, Chautauqua, Chemung, Chenango and Clinton.]\n\n2. **Counties requiring additional oversight:** [Counties with MOE between 5–10% should be used with caution and monitored for stability. For instance, Essex (5.3%), Greene (7.0%), and Schuyler (5.8%) fall into this category, suggesting periodic review of outcomes. Besides, Seneca and Yates are also included in this category.]\n\n3. **Counties needing alternative approaches:** [Counties with MOE above 10% require manual review or supplemental data. Only Hamilton shows an income MOE of 11.4%, which signals insufficient reliability for direct algorithmic use.]\n\n## Questions for Further Investigation\n\n[1. How do MOE patterns differ between urban and rural counties, and what does this mean for equitable decision-making?\n2. Do time trends (e.g., comparing single-year vs. five-year ACS data) change the reliability patterns we observed?\n3. Are smaller minority populations systematically associated with higher MOEs, and how might improved sampling address this?]\n\n# Technical Notes\n\n**Data Sources:** \n- U.S. Census Bureau, American Community Survey 2018-2022 5-Year Estimates\n- Retrieved via tidycensus R package on [2025.09.20]\n\n**Reproducibility:** \n- All analysis conducted in R version [R Studio 4.3.1]\n- Census API key required for replication\n- Complete code and documentation available at: [your portfolio URL]\n\n**Methodology Notes:**\n[Defined high MOE as >10% relative margin of error.\nUsed county-level median income MOE% as the primary reliability measure.]\n\n**Limitations:**\n[Tracts with small minority populations produce very high MOE%, which may lead to unreliable result.]\n\n---",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}