{
  "hash": "481a035ad86585b8eaa2ab1449d6c97e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Xiaoqing (Kelsey) Chen\"\ndate: \"2025-10-04\"\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\n**Learning Objectives:**\n- Apply spatial operations to answer policy-relevant research questions\n- Integrate census demographic data with spatial analysis\n- Create publication-quality visualizations and maps\n- Work with spatial data from multiple sources\n- Communicate findings effectively for policy audiences\n\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\nYour analysis should identify counties that should be priorities for healthcare investment and policy intervention.\n\n### Required Analysis Steps\n\nComplete the following analysis, documenting each step with code and brief explanations:\n\n#### Step 1: Data Collection (5 points)\n\nLoad the required spatial data:\n- Pennsylvania county boundaries\n- Pennsylvania hospitals (from lecture data)\n- Pennsylvania census tracts\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(sf)\nlibrary(tigris)\nlibrary(tidycensus)\nlibrary(dplyr)\nlibrary(knitr)\n\ncensus_api_key(Sys.getenv(\"e17c1c6ce413dc3faca31a17a58ab3374404bb9e\"), install = FALSE)\n\n# Load spatial data\n\npa_counties <- st_read(\"data/Pennsylvania_County_Boundaries.shp\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Pennsylvania_County_Boundaries' from data source \n  `D:\\Code\\musa-5080-fall-2025-portfolio-setup-student-portfolio-template\\portfolio-setup-XiaoqingChen-729\\assignments\\assignment_2\\data\\Pennsylvania_County_Boundaries.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 67 features and 19 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8963377 ymin: 4825316 xmax: -8314404 ymax: 5201413\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\npa_hospitals <- st_read(\"data/hospitals.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `hospitals' from data source \n  `D:\\Code\\musa-5080-fall-2025-portfolio-setup-student-portfolio-template\\portfolio-setup-XiaoqingChen-729\\assignments\\assignment_2\\data\\hospitals.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 223 features and 11 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -80.49621 ymin: 39.75163 xmax: -74.86704 ymax: 42.13403\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\npa_tracts <- st_read(\"data/districts.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `U.S._Congressional_Districts_for_Pennsylvania' from data source \n  `D:\\Code\\musa-5080-fall-2025-portfolio-setup-student-portfolio-template\\portfolio-setup-XiaoqingChen-729\\assignments\\assignment_2\\data\\districts.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 17 features and 8 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: -80.51939 ymin: 39.71986 xmax: -74.68956 ymax: 42.26935\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check that all data loaded correctly\nclass(pa_counties)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"sf\"         \"data.frame\"\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(pa_hospitals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 223\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(pa_tracts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 17\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(pa_counties)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 / Pseudo-Mercator \n  wkt:\nPROJCRS[\"WGS 84 / Pseudo-Mercator\",\n    BASEGEOGCRS[\"WGS 84\",\n        ENSEMBLE[\"World Geodetic System 1984 ensemble\",\n            MEMBER[\"World Geodetic System 1984 (Transit)\"],\n            MEMBER[\"World Geodetic System 1984 (G730)\"],\n            MEMBER[\"World Geodetic System 1984 (G873)\"],\n            MEMBER[\"World Geodetic System 1984 (G1150)\"],\n            MEMBER[\"World Geodetic System 1984 (G1674)\"],\n            MEMBER[\"World Geodetic System 1984 (G1762)\"],\n            MEMBER[\"World Geodetic System 1984 (G2139)\"],\n            MEMBER[\"World Geodetic System 1984 (G2296)\"],\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]],\n            ENSEMBLEACCURACY[2.0]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4326]],\n    CONVERSION[\"Popular Visualisation Pseudo-Mercator\",\n        METHOD[\"Popular Visualisation Pseudo Mercator\",\n            ID[\"EPSG\",1024]],\n        PARAMETER[\"Latitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"False easting\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Web mapping and visualisation.\"],\n        AREA[\"World between 85.06°S and 85.06°N.\"],\n        BBOX[-85.06,-180,85.06,180]],\n    ID[\"EPSG\",3857]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(pa_hospitals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"geodetic latitude (Lat)\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"geodetic longitude (Lon)\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(pa_tracts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"geodetic latitude (Lat)\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"geodetic longitude (Lon)\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many hospitals are in your dataset? 【223】\n- How many census tracts? 【17】\n- What coordinate reference system is each dataset in? 【WGS 84】 \n\n---\n\n#### Step 2: Get Demographic Data \n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n**Required variables:**\n- Total population\n- Median household income\n- Population 65 years and over (you may need to sum multiple age categories)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS\nvars <- c(\n  total_pop = \"B01003_001\",\n  med_income = \"B19013_001\"\n)\n\nage_vars <- c(\n  \"B01001_020\", \"B01001_021\", \"B01001_022\", \"B01001_023\", \"B01001_024\", \"B01001_025\",  # Males 65+\n  \"B01001_044\", \"B01001_045\", \"B01001_046\", \"B01001_047\", \"B01001_048\", \"B01001_049\"   # Females 65+\n)\n\npa_demo <- get_acs(\n  geography = \"tract\",\n  variables = vars,\n  state = \"PA\",\n  year = 2022,\n  geometry = TRUE\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  |                                                                            \n  |                                                                      |   0%\n  |                                                                            \n  |=                                                                     |   1%\n  |                                                                            \n  |=                                                                     |   2%\n  |                                                                            \n  |==                                                                    |   2%\n  |                                                                            \n  |==                                                                    |   3%\n  |                                                                            \n  |===                                                                   |   4%\n  |                                                                            \n  |===                                                                   |   5%\n  |                                                                            \n  |====                                                                  |   5%\n  |                                                                            \n  |====                                                                  |   6%\n  |                                                                            \n  |=====                                                                 |   7%\n  |                                                                            \n  |======                                                                |   8%\n  |                                                                            \n  |======                                                                |   9%\n  |                                                                            \n  |=======                                                               |  10%\n  |                                                                            \n  |========                                                              |  11%\n  |                                                                            \n  |========                                                              |  12%\n  |                                                                            \n  |=========                                                             |  12%\n  |                                                                            \n  |=========                                                             |  13%\n  |                                                                            \n  |==========                                                            |  14%\n  |                                                                            \n  |===========                                                           |  15%\n  |                                                                            \n  |===========                                                           |  16%\n  |                                                                            \n  |============                                                          |  17%\n  |                                                                            \n  |=============                                                         |  18%\n  |                                                                            \n  |=============                                                         |  19%\n  |                                                                            \n  |==============                                                        |  20%\n  |                                                                            \n  |===============                                                       |  21%\n  |                                                                            \n  |===============                                                       |  22%\n  |                                                                            \n  |================                                                      |  23%\n  |                                                                            \n  |=================                                                     |  24%\n  |                                                                            \n  |==================                                                    |  25%\n  |                                                                            \n  |==================                                                    |  26%\n  |                                                                            \n  |===================                                                   |  27%\n  |                                                                            \n  |====================                                                  |  28%\n  |                                                                            \n  |====================                                                  |  29%\n  |                                                                            \n  |=====================                                                 |  30%\n  |                                                                            \n  |======================                                                |  31%\n  |                                                                            \n  |======================                                                |  32%\n  |                                                                            \n  |=======================                                               |  33%\n  |                                                                            \n  |========================                                              |  34%\n  |                                                                            \n  |========================                                              |  35%\n  |                                                                            \n  |=========================                                             |  36%\n  |                                                                            \n  |==========================                                            |  37%\n  |                                                                            \n  |==========================                                            |  38%\n  |                                                                            \n  |===========================                                           |  39%\n  |                                                                            \n  |============================                                          |  40%\n  |                                                                            \n  |=============================                                         |  41%\n  |                                                                            \n  |=============================                                         |  42%\n  |                                                                            \n  |==============================                                        |  43%\n  |                                                                            \n  |===============================                                       |  44%\n  |                                                                            \n  |===============================                                       |  45%\n  |                                                                            \n  |================================                                      |  46%\n  |                                                                            \n  |=================================                                     |  47%\n  |                                                                            \n  |=================================                                     |  48%\n  |                                                                            \n  |==================================                                    |  49%\n  |                                                                            \n  |===================================                                   |  50%\n  |                                                                            \n  |===================================                                   |  51%\n  |                                                                            \n  |====================================                                  |  52%\n  |                                                                            \n  |=====================================                                 |  53%\n  |                                                                            \n  |=====================================                                 |  54%\n  |                                                                            \n  |======================================                                |  54%\n  |                                                                            \n  |=======================================                               |  55%\n  |                                                                            \n  |========================================                              |  56%\n  |                                                                            \n  |========================================                              |  57%\n  |                                                                            \n  |=========================================                             |  58%\n  |                                                                            \n  |==========================================                            |  59%\n  |                                                                            \n  |==========================================                            |  60%\n  |                                                                            \n  |===========================================                           |  61%\n  |                                                                            \n  |============================================                          |  62%\n  |                                                                            \n  |============================================                          |  63%\n  |                                                                            \n  |=============================================                         |  64%\n  |                                                                            \n  |==============================================                        |  65%\n  |                                                                            \n  |==============================================                        |  66%\n  |                                                                            \n  |===============================================                       |  67%\n  |                                                                            \n  |================================================                      |  68%\n  |                                                                            \n  |================================================                      |  69%\n  |                                                                            \n  |=================================================                     |  70%\n  |                                                                            \n  |==================================================                    |  71%\n  |                                                                            \n  |===================================================                   |  72%\n  |                                                                            \n  |===================================================                   |  73%\n  |                                                                            \n  |====================================================                  |  74%\n  |                                                                            \n  |=====================================================                 |  75%\n  |                                                                            \n  |=====================================================                 |  76%\n  |                                                                            \n  |======================================================                |  77%\n  |                                                                            \n  |=======================================================               |  78%\n  |                                                                            \n  |=======================================================               |  79%\n  |                                                                            \n  |========================================================              |  80%\n  |                                                                            \n  |=========================================================             |  81%\n  |                                                                            \n  |=========================================================             |  82%\n  |                                                                            \n  |==========================================================            |  83%\n  |                                                                            \n  |===========================================================           |  84%\n  |                                                                            \n  |===========================================================           |  85%\n  |                                                                            \n  |============================================================          |  86%\n  |                                                                            \n  |=============================================================         |  87%\n  |                                                                            \n  |=============================================================         |  88%\n  |                                                                            \n  |==============================================================        |  89%\n  |                                                                            \n  |===============================================================       |  90%\n  |                                                                            \n  |================================================================      |  91%\n  |                                                                            \n  |================================================================      |  92%\n  |                                                                            \n  |=================================================================     |  93%\n  |                                                                            \n  |==================================================================    |  94%\n  |                                                                            \n  |==================================================================    |  95%\n  |                                                                            \n  |===================================================================   |  96%\n  |                                                                            \n  |====================================================================  |  97%\n  |                                                                            \n  |====================================================================  |  98%\n  |                                                                            \n  |===================================================================== |  99%\n  |                                                                            \n  |======================================================================| 100%\n```\n\n\n:::\n\n```{.r .cell-code}\npa_age <- get_acs(\n  geography = \"tract\",\n  variables = age_vars,\n  state = \"PA\",\n  year = 2022\n)\n# Join to tract boundaries\npa_age65plus <- pa_age %>%\n  group_by(GEOID) %>%\n  summarise(age65plus = sum(estimate, na.rm = TRUE))\n\npa_demo_wide <- pa_demo %>%\n  select(GEOID, variable, estimate) %>%\n  tidyr::pivot_wider(names_from = variable, values_from = estimate)\n\npa_demo_final <- pa_demo_wide %>%\n  left_join(pa_age65plus, by = \"GEOID\")\n\npa_income <- pa_demo %>%\n  dplyr::filter(variable == \"med_income\") %>%\n  dplyr::select(GEOID, NAME, estimate)\nnrow(pa_income)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3446\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(is.na(pa_income$estimate))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 63\n```\n\n\n:::\n\n```{.r .cell-code}\nmedian(pa_income$estimate, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 70188\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What year of ACS data are you using?  【2022】\n- How many tracts have missing income data?  【63】\n- What is the median income across all PA census tracts?  【70188】\n\n---\n\n#### Step 3: Define Vulnerable Populations \n\nIdentify census tracts with vulnerable populations based on TWO criteria:\n1. Low median household income (choose an appropriate threshold)\n2. Significant elderly population (choose an appropriate threshold)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\nmedian_income_pa <- median(pa_income$estimate, na.rm = TRUE)\nincome_threshold <- median_income_pa * 0.8\nelderly_threshold <- 0.15\n\n\n\npa_demo_final <- pa_demo_final %>%\n  mutate(elderly_share = age65plus / total_pop)\n\nvulnerable_tracts <- pa_demo_final %>%\n  filter(\n    med_income < income_threshold,\n    elderly_share > elderly_threshold\n  )\n\nn_vulnerable <- nrow(vulnerable_tracts)\npct_vulnerable <- n_vulnerable / nrow(pa_demo_final) * 100\n\nn_vulnerable\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 480\n```\n\n\n:::\n\n```{.r .cell-code}\npct_vulnerable\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13.92919\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- What income threshold did you choose and why?  【I choose the value of 80% of the country median income, so income threshold equals to $56,150. The reason is to low the influence of extremely high-income regions.】\n- What elderly population threshold did you choose and why?  【I choose 15% of total population aged 65 or older as elderly population. The reason it that the percentage of aged people of whole country was about 17%.】\n- How many tracts meet your vulnerability criteria?  【There are 480 tracts met my vulnerability criteria.】\n- What percentage of PA census tracts are considered vulnerable by your definition?  【There are nearly 14% of the PA census tracts are considered vulnerable.】\n\n---\n\n#### Step 4: Calculate Distance to Hospitals \n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform to appropriate projected CRS\npa_hospitals <- st_read(\"data/hospitals.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `hospitals' from data source \n  `D:\\Code\\musa-5080-fall-2025-portfolio-setup-student-portfolio-template\\portfolio-setup-XiaoqingChen-729\\assignments\\assignment_2\\data\\hospitals.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 223 features and 11 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -80.49621 ymin: 39.75163 xmax: -74.86704 ymax: 42.13403\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nvulnerable_tracts_proj <- st_transform(vulnerable_tracts, 26918)\npa_hospitals_proj <- st_transform(pa_hospitals, 26918)\n\n\n# Calculate distance from each tract centroid to nearest hospital\ntract_centroids <- st_centroid(vulnerable_tracts_proj)\ndist_matrix <- st_distance(tract_centroids, pa_hospitals_proj)\nnearest_dist <- apply(dist_matrix, 1, min)  \nvulnerable_tracts_proj <- vulnerable_tracts_proj %>%\n  mutate(dist_to_nearest_hospital_m = as.numeric(nearest_dist),\n         dist_to_nearest_hospital_miles = dist_to_nearest_hospital_m / 1609.34)\n\nsummary(vulnerable_tracts_proj$dist_to_nearest_hospital_miles)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n 0.02094  1.01250  2.07449  4.02155  4.97522 25.63590 \n```\n\n\n:::\n\n```{.r .cell-code}\nsum(vulnerable_tracts_proj$dist_to_nearest_hospital_miles > 15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 21\n```\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use an appropriate projected coordinate system for Pennsylvania\n- Calculate distances in miles\n- Explain why you chose your projection\n\n**Questions to answer:**\n- What is the average distance to the nearest hospital for vulnerable tracts?  【Nearly 4 miles.】\n- What is the maximum distance?  【Approximately 26 miles.】\n- How many vulnerable tracts are more than 15 miles from the nearest hospital?  【21】\n\n---\n\n#### Step 5: Identify Underserved Areas \n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create underserved variable\nvulnerable_tracts_proj <- vulnerable_tracts_proj %>%\n  mutate(\n    underserved = dist_to_nearest_hospital_miles > 15\n  )\n\nnum_underserved <- sum(vulnerable_tracts_proj$underserved, na.rm = TRUE)\npct_underserved <- num_underserved / nrow(vulnerable_tracts_proj) * 100\n\nlist(\n  underserved_tracts = num_underserved,\n  percent_underserved = round(pct_underserved, 2)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$underserved_tracts\n[1] 21\n\n$percent_underserved\n[1] 4.38\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many tracts are underserved? 【21】\n- What percentage of vulnerable tracts are underserved?  【Nearly 4.4%.】\n- Does this surprise you? Why or why not?  【No. Nearly 4% is a tiny percentage compared to the whole PA. And most of the residents live in urban areas where hospitals are relatively close.】\n\n---\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join tracts to counties\npa_counties <- st_read(\"data/Pennsylvania_County_Boundaries.shp\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Pennsylvania_County_Boundaries' from data source \n  `D:\\Code\\musa-5080-fall-2025-portfolio-setup-student-portfolio-template\\portfolio-setup-XiaoqingChen-729\\assignments\\assignment_2\\data\\Pennsylvania_County_Boundaries.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 67 features and 19 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8963377 ymin: 4825316 xmax: -8314404 ymax: 5201413\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\npa_counties_proj <- st_transform(pa_counties, 26918)\n\ncounties_index <- pa_counties_proj %>%\n  st_drop_geometry() %>%\n  distinct(county_geoid = FIPS_COUNT, county_name = COUNTY_NAM)\n\nvuln_with_county <- sf::st_join(\n  vulnerable_tracts_proj,                     \n  pa_counties_proj %>% dplyr::select(\n    county_geoid = FIPS_COUNT, county_name = COUNTY_NAM\n  ),\n  join = sf::st_within, left = TRUE\n)\n\ncounty_stats <- vuln_with_county %>%\n  st_drop_geometry() %>%\n  group_by(county_geoid, county_name) %>%\n  summarise(\n    num_vulnerable  = n(),\n    num_underserved = sum(underserved, na.rm = TRUE),\n    avg_dist_miles  = mean(dist_to_nearest_hospital_miles, na.rm = TRUE)\n  )\n\nlibrary(tidyr)\n\n# Aggregate statistics by county\ncounty_stats_all <- counties_index %>%\n  left_join(county_stats, by = c(\"county_geoid\",\"county_name\")) %>%\n  mutate(\n    num_vulnerable   = replace_na(num_vulnerable, 0L),\n    num_underserved  = replace_na(num_underserved, 0L),\n    pct_underserved  = if_else(num_vulnerable > 0,\n                               100 * num_underserved / num_vulnerable,\n                               0),                 \n    avg_dist_miles   = if_else(num_vulnerable > 0, avg_dist_miles, NA_real_)\n  )\n\ntop5_by_pct <- county_stats_all %>%\n  filter(num_vulnerable > 0) %>%\n  slice_max(pct_underserved, n = 5)\n\ntop5_by_count <- county_stats_all %>%\n  slice_max(num_underserved, n = 5)\n\ntop5_by_pct\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  county_geoid county_name num_vulnerable num_underserved avg_dist_miles\n1          023     CAMERON              1               1      18.682591\n2          089      MONROE              1               1      17.677540\n3          033  CLEARFIELD              5               3      13.771368\n4          015    BRADFORD              3               1      11.187304\n5          049        ERIE             10               1       4.027113\n  pct_underserved\n1       100.00000\n2       100.00000\n3        60.00000\n4        33.33333\n5        10.00000\n```\n\n\n:::\n\n```{.r .cell-code}\ntop5_by_count\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  county_geoid county_name num_vulnerable num_underserved avg_dist_miles\n1          033  CLEARFIELD              5               3      13.771368\n2          015    BRADFORD              3               1      11.187304\n3          023     CAMERON              1               1      18.682591\n4          049        ERIE             10               1       4.027113\n5          089      MONROE              1               1      17.677540\n  pct_underserved\n1        60.00000\n2        33.33333\n3       100.00000\n4        10.00000\n5       100.00000\n```\n\n\n:::\n:::\n\n\n**Required county-level statistics:**\n- Number of vulnerable tracts\n- Number of underserved tracts  \n- Percentage of vulnerable tracts that are underserved\n- Average distance to nearest hospital for vulnerable tracts\n- Total vulnerable population\n\n**Questions to answer:**\n- Which 5 counties have the highest percentage of underserved vulnerable tracts?  【The five counties with the highest percentage of underserved vulnerable tracts are Cameron, Monroe, Clearfield, Bardford, and Erie Counties.】\n- Which counties have the most vulnerable people living far from hospitals?  【CLEARFIELD】\n- Are there any patterns in where underserved counties are located?  【Underserved counties are mainly concentrated in the northern and central rural regions of Pennsylvania. In contrast, urban counties like Philadelphia and Allegheny have few or no underserved tracts because hospitals are more densely distributed.】\n\n---\n\n#### Step 7: Create Summary Table \n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create and format priority counties table\nlibrary(knitr)\nlibrary(scales)\n\npriority_counties <- county_stats_all %>%\n  arrange(desc(pct_underserved)) %>%       \n  slice_head(n = 10) %>%               \n  mutate(\n    pct_underserved = percent(pct_underserved / 100, accuracy = 0.1),\n    avg_dist_miles  = round(avg_dist_miles, 1)\n  ) %>%\n  select(\n    \"County Name\" = county_name,\n    \"Vulnerable Tracts\" = num_vulnerable,\n    \"Underserved Tracts\" = num_underserved,\n    \"Percent Underserved\" = pct_underserved,\n    \"Avg. Distance to Hospital (miles)\" = avg_dist_miles\n  )\n\nkable(priority_counties,\n      caption = \"Top 10 Pennsylvania Counties Prioritized for Healthcare Investment\",\n      align = \"lrrrr\",\n      format = \"markdown\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 10 Pennsylvania Counties Prioritized for Healthcare Investment\n\n|County Name | Vulnerable Tracts| Underserved Tracts| Percent Underserved| Avg. Distance to Hospital (miles)|\n|:-----------|-----------------:|------------------:|-------------------:|---------------------------------:|\n|CAMERON     |                 1|                  1|              100.0%|                              18.7|\n|MONROE      |                 1|                  1|              100.0%|                              17.7|\n|CLEARFIELD  |                 5|                  3|               60.0%|                              13.8|\n|BRADFORD    |                 3|                  1|               33.3%|                              11.2|\n|ERIE        |                10|                  1|               10.0%|                               4.0|\n|MONTGOMERY  |                 2|                  0|                0.0%|                               1.3|\n|BUCKS       |                 0|                  0|                0.0%|                                NA|\n|TIOGA       |                 2|                  0|                0.0%|                               5.7|\n|UNION       |                 2|                  0|                0.0%|                               2.6|\n|VENANGO     |                 5|                  0|                0.0%|                               6.6|\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use `knitr::kable()` or similar for formatting\n- Include descriptive column names\n- Format numbers appropriately (commas for population, percentages, etc.)\n- Add an informative caption\n- Sort by priority (you decide the metric)\n\n---\n\n## Part 2: Comprehensive Visualization \n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth \n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create county-level access map\nlibrary(ggplot2)\nlibrary(sf)\nlibrary(viridis)\n\ncounty_map <- pa_counties_proj %>%\n  left_join(county_stats_all, by = c(\"FIPS_COUNT\" = \"county_geoid\", \"COUNTY_NAM\" = \"county_name\"))\n\ngrey_blue <- c(\n  \"#F4F6F6\", \n  \"#D8E0E5\", \n  \"#B9C9D2\", \n  \"#9AAEBF\", \n  \"#7F97A6\", \n  \"#5E7C8A\", \n  \"#405E70\", \n  \"#2E4757\"  \n)\n\nggplot() +\n  geom_sf(data = county_map, aes(fill = pct_underserved), color = \"white\", size = 0.2) +\n  geom_sf(data = pa_hospitals_proj, color = \"grey30\", size = 0.8, alpha = 0.5) +\n  scale_fill_gradientn(\n    colours = grey_blue,\n    name = \"% Underserved\",\n    limits = c(0, 100),\n    labels = scales::percent_format(scale = 1),\n    na.value = \"grey95\"\n  ) +\n  theme_void() +\n  theme(\n    legend.position = \"right\",\n    plot.title = element_text(size = 14, face = \"bold\", color = \"grey20\", hjust = 0.5),\n    plot.subtitle = element_text(size = 11, color = \"grey40\", hjust = 0.5),\n    plot.caption = element_text(size = 9, color = \"grey50\", hjust = 0.5),\n    panel.background = element_rect(fill = \"white\", color = NA)\n  ) +\n  labs(\n    title = \"Healthcare Access Across Pennsylvania Counties\",\n    subtitle = \"Percentage of vulnerable tracts more than 15 miles from nearest hospital\",\n    caption = \"Data: ACS 2022, hospitals.geojson\"\n  )\n```\n\n::: {.cell-output-display}\n![](Chen_Xiaoqing_Assignment2_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Fill counties by percentage of vulnerable tracts that are underserved\n- Include hospital locations as points\n- Use an appropriate color scheme\n- Include clear title, subtitle, and caption\n- Use `theme_void()` or similar clean theme\n- Add a legend with formatted labels\n\n---\n\n### Map 2: Detailed Vulnerability Map \n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create detailed tract-level map\ntract_palette <- c(\n  \"FALSE\" = \"#B7C4CF\",  \n  \"TRUE\"  = \"#8B3A3A\"   \n)\n\nggplot() +\n  geom_sf(data = pa_counties_proj, fill = \"white\", color = \"grey85\", size = 0.2) +\n  \n  geom_sf(data = vulnerable_tracts_proj, \n          aes(fill = as.factor(underserved)), \n          color = NA, alpha = 0.8) +\n  \n  geom_sf(data = pa_hospitals_proj, color = \"grey30\", size = 0.7, alpha = 0.5) +\n  \n  scale_fill_manual(\n    values = tract_palette,\n    name = \"Underserved Status\",\n    labels = c(\"Not Underserved\", \"Underserved\")\n  ) +\n  theme_void() +\n  theme(\n    legend.position = \"right\",\n    plot.title = element_text(size = 14, face = \"bold\", color = \"#333333\", hjust = 0.5),\n    plot.subtitle = element_text(size = 11, color = \"grey40\", hjust = 0.5),\n    plot.caption = element_text(size = 9, color = \"grey50\", hjust = 0.5),\n    legend.title = element_text(size = 10, face = \"bold\"),\n    legend.text = element_text(size = 9)\n  ) +\n  labs(\n    title = \"Underserved Vulnerable Census Tracts in Pennsylvania\",\n    subtitle = \"Tracts more than 15 miles from nearest hospital (highlighted in warm red-brown)\",\n    caption = \"Data: ACS 2022, hospitals.geojson\"\n  )\n```\n\n::: {.cell-output-display}\n![](Chen_Xiaoqing_Assignment2_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Show underserved vulnerable tracts in a contrasting color\n- Include county boundaries for context\n- Show hospital locations\n- Use appropriate visual hierarchy (what should stand out?)\n- Include informative title and subtitle\n\n---\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\nggplot(vulnerable_tracts_proj, aes(x = dist_to_nearest_hospital_miles)) +\n  geom_histogram(\n    fill = \"#8B3A3A\",      \n    color = \"white\", \n    bins = 30,            \n    alpha = 0.8\n  ) +\n  geom_vline(aes(xintercept = 15), color = \"#405E70\", linetype = \"dashed\", size = 0.8) +\n  theme_minimal() +\n  labs(\n    title = \"Distribution of Distance to Nearest Hospital\",\n    subtitle = \"Vulnerable census tracts across Pennsylvania\",\n    x = \"Distance to nearest hospital (miles)\",\n    y = \"Number of tracts\",\n    caption = \"Dashed line represents 15-mile threshold for underserved classification\"\n  ) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 14, color = \"#2E4757\", hjust = 0.5),\n    plot.subtitle = element_text(size = 11, color = \"grey40\", hjust = 0.5),\n    axis.title = element_text(size = 10, hjust = 0.5),\n    panel.grid.minor = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](Chen_Xiaoqing_Assignment2_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n**Suggested chart types:**\n- Histogram or density plot of distances\n- Box plot comparing distances across regions\n- Bar chart of underserved tracts by county\n- Scatter plot of distance vs. vulnerable population size\n\n**Requirements:**\n- Clear axes labels with units\n- Appropriate title\n- Professional formatting\n- Brief interpretation (1-2 sentences as a caption or in text)\n\n---\n\n## Part 3: Bring Your Own Data Analysis \n\nChoose your own additional spatial dataset and conduct a supplementary analysis.\n\n### Challenge Options\n\nChoose ONE of the following challenge exercises, or propose your own research question using OpenDataPhilly data (https://opendataphilly.org/datasets/). \n\n**Note these are just loose suggestions to spark ideas - follow or make your own as the data permits and as your ideas evolve. This analysis should include bringing in your own dataset, ensuring the projection/CRS of your layers align and are appropriate for the analysis (not lat/long or geodetic coordinate systems). The analysis portion should include some combination of spatial and attribute operations to answer a relatively straightforward question**\n\n---\n\n#### Education & Youth Services\n\n**Option A: Educational Desert Analysis**\n- **Data:** Schools, Libraries, Recreation Centers, Census tracts (child population)\n- **Question:** \"Which neighborhoods lack adequate educational infrastructure for children?\"\n- **Operations:** Buffer schools/libraries (0.5 mile walking distance), identify coverage gaps, overlay with child population density\n- **Policy relevance:** School district planning, library placement, after-school program siting\n\n**Option B: School Safety Zones**\n- **Data:** Schools, Crime Incidents, Bike Network\n- **Question:** \"Are school zones safe for walking/biking, or are they crime hotspots?\"\n- **Operations:** Buffer schools (1000ft safety zone), spatial join with crime incidents, assess bike infrastructure coverage\n- **Policy relevance:** Safe Routes to School programs, crossing guard placement\n\n---\n\n#### Environmental Justice\n\n**Option C: Green Space Equity** \n- **Data:** Parks, Street Trees, Census tracts (race/income demographics)\n- **Question:** \"Do low-income and minority neighborhoods have equitable access to green space?\"\n- **Operations:** Buffer parks (10-minute walk = 0.5 mile), calculate tree canopy or park acreage per capita, compare by demographics\n- **Policy relevance:** Climate resilience, environmental justice, urban forestry investment\n---\n\n#### Public Safety & Justice\n\n**Option D: Crime & Community Resources**\n- **Data:** Crime Incidents, Recreation Centers, Libraries, Street Lights\n- **Question:** \"Are high-crime areas underserved by community resources?\"\n- **Operations:** Aggregate crime counts to census tracts or neighborhoods, count community resources per area, spatial correlation analysis\n- **Policy relevance:** Community investment, violence prevention strategies\n---\n\n#### Infrastructure & Services\n\n**Option E: Polling Place Accessibility**\n- **Data:** Polling Places, SEPTA stops, Census tracts (elderly population, disability rates)\n- **Question:** \"Are polling places accessible for elderly and disabled voters?\"\n- **Operations:** Buffer polling places and transit stops, identify vulnerable populations, find areas lacking access\n- **Policy relevance:** Voting rights, election infrastructure, ADA compliance\n\n---\n\n#### Health & Wellness\n\n**Option F: Recreation & Population Health**\n- **Data:** Recreation Centers, Playgrounds, Parks, Census tracts (demographics)\n- **Question:** \"Is lack of recreation access associated with vulnerable populations?\"\n- **Operations:** Calculate recreation facilities per capita by neighborhood, buffer facilities for walking access, overlay with demographic indicators\n- **Policy relevance:** Public health investment, recreation programming, obesity prevention\n\n---\n\n#### Emergency Services\n\n**Option G: EMS Response Coverage**\n- **Data:** Fire Stations, EMS stations, Population density, High-rise buildings\n- **Question:** \"Are population-dense areas adequately covered by emergency services?\"\n- **Operations:** Create service area buffers (5-minute drive = ~2 miles), assess population coverage, identify gaps in high-density areas\n- **Policy relevance:** Emergency preparedness, station siting decisions\n\n---\n\n#### Arts & Culture\n\n**Option H: Cultural Asset Distribution**\n- **Data:** Public Art, Museums, Historic sites/markers, Neighborhoods\n- **Question:** \"Do all neighborhoods have equitable access to cultural amenities?\"\n- **Operations:** Count cultural assets per neighborhood, normalize by population, compare distribution across demographic groups\n- **Policy relevance:** Cultural equity, tourism, quality of life, neighborhood identity\n\n---\n\n### Data Sources\n\n**OpenDataPhilly:** https://opendataphilly.org/datasets/\n- Most datasets available as GeoJSON, Shapefile, or CSV with coordinates\n- Always check the Metadata for a data dictionary of the fields.\n\n**Additional Sources:**\n- **Pennsylvania Open Data:** https://data.pa.gov/\n- **Census Bureau (via tidycensus):** Demographics, economic indicators, commute patterns\n- **TIGER/Line (via tigris):** Geographic boundaries\n\n### Recommended Starting Points\n\n**If you're feeling confident:** Choose an advanced challenge with multiple data layers. \n**If you are a beginner, choose something more manageable that helps you understand the basics**\n\n\n**If you have a different idea:** Propose your own question! Just make sure:\n- You can access the spatial data\n- You can perform at least 2 spatial operations\n\n### Your Analysis\n\n**Your Task:**\n\n1. **Find and load additional data**\n   - Document your data source\n   - Check and standardize the CRS\n   - Provide basic summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load your additional dataset\nlibrary(sf)\nlibrary(dplyr)\nlibrary(tidycensus)\nlibrary(tigris)\n\nbike_stations <- st_read(\"indego_stations.geojson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `indego_stations' from data source \n  `D:\\Code\\musa-5080-fall-2025-portfolio-setup-student-portfolio-template\\portfolio-setup-XiaoqingChen-729\\assignments\\assignment_2\\indego_stations.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 282 features and 33 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -75.24522 ymin: 39.88994 xmax: -75.10121 ymax: 40.03055\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\nglimpse(bike_stations)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 282\nColumns: 34\n$ id                     <int> 3005, 3006, 3007, 3008, 3009, 3010, 3012, 3014,…\n$ name                   <chr> \"Welcome Park, NPS\", \"40th & Spruce\", \"11th & P…\n$ totalDocks             <int> 13, 17, 20, 17, 14, 22, 27, 25, 11, 15, 15, 18,…\n$ docksAvailable         <int> 0, 16, 18, 9, 3, 19, 23, 22, 5, 11, 12, 4, 7, 1…\n$ bikesAvailable         <int> 11, 1, 0, 7, 11, 3, 4, 3, 6, 4, 2, 12, 8, 20, 1…\n$ classicBikesAvailable  <int> 3, 0, 0, 1, 1, 1, 1, 3, 0, 1, 1, 2, 2, 9, 0, 1,…\n$ smartBikesAvailable    <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ electricBikesAvailable <int> 8, 1, 0, 6, 10, 2, 3, 0, 6, 3, 1, 10, 6, 11, 13…\n$ rewardBikesAvailable   <int> 12, 1, 0, 8, 11, 3, 4, 3, 6, 4, 2, 12, 8, 20, 1…\n$ rewardDocksAvailable   <int> 0, 16, 20, 9, 3, 17, 23, 22, 5, 11, 13, 5, 7, 1…\n$ kioskStatus            <chr> \"FullService\", \"FullService\", \"FullService\", \"F…\n$ kioskPublicStatus      <chr> \"Active\", \"Active\", \"Active\", \"Active\", \"Active…\n$ kioskConnectionStatus  <chr> \"Active\", \"Active\", \"Active\", \"Active\", \"Active…\n$ kioskType              <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…\n$ addressStreet          <chr> \"191 S. 2nd St.\", \"246 S. 40th St.\", \"328 S. 11…\n$ addressCity            <chr> \"Philadelphia\", \"Philadelphia\", \"Philadelphia\",…\n$ addressState           <chr> \"PA\", \"PA\", \"PA\", \"PA\", \"PA\", \"PA\", \"PA\", \"PA\",…\n$ addressZipCode         <chr> \"19106\", \"19104\", \"19107\", \"19122\", \"19104\", \"1…\n$ bikes                  <chr> \"[ { \\\"dockNumber\\\": 1, \\\"isElectric\\\": true, \\…\n$ closeTime              <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ eventEnd               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ eventStart             <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ isEventBased           <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…\n$ isVirtual              <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…\n$ kioskId                <int> 3005, 3006, 3007, 3008, 3009, 3010, 3012, 3014,…\n$ notes                  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ openTime               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ publicText             <chr> \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\", \"\",…\n$ timeZone               <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ trikesAvailable        <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ latitude               <dbl> 39.94733, 39.95220, 39.94517, 39.98081, 39.9557…\n$ longitude              <dbl> -75.14403, -75.20311, -75.15993, -75.15067, -75…\n$ coordinates            <list> <-75.14403, 39.94733>, <-75.20311, 39.95220>, …\n$ geometry               <POINT [°]> POINT (-75.14403 39.94733), POINT (-75.20…\n```\n\n\n:::\n\n```{.r .cell-code}\nst_crs(bike_stations)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: WGS 84 \n  wkt:\nGEOGCRS[\"WGS 84\",\n    DATUM[\"World Geodetic System 1984\",\n        ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"geodetic latitude (Lat)\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"geodetic longitude (Lon)\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4326]]\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(bike_stations)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 282\n```\n\n\n:::\n\n```{.r .cell-code}\nphilly_tracts <- tracts(state = \"PA\", county = \"Philadelphia\", year = 2022, cb = TRUE)\nst_crs(philly_tracts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: NAD83 \n  wkt:\nGEOGCRS[\"NAD83\",\n    DATUM[\"North American Datum 1983\",\n        ELLIPSOID[\"GRS 1980\",6378137,298.257222101,\n            LENGTHUNIT[\"metre\",1]]],\n    PRIMEM[\"Greenwich\",0,\n        ANGLEUNIT[\"degree\",0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\"latitude\",north,\n            ORDER[1],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        AXIS[\"longitude\",east,\n            ORDER[2],\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n    ID[\"EPSG\",4269]]\n```\n\n\n:::\n\n```{.r .cell-code}\nbike_stations <- st_transform(bike_stations, st_crs(philly_tracts))\nplot(st_geometry(philly_tracts))\nplot(st_geometry(bike_stations), add = TRUE, col = \"blue\", pch = 16, cex = 0.5)\n```\n\n::: {.cell-output-display}\n![](Chen_Xiaoqing_Assignment2_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n\n```{.r .cell-code}\nbike_stations <- st_transform(bike_stations, 26918)\nphilly_tracts <- st_transform(philly_tracts, 26918)\n```\n:::\n\n\n**Questions to answer:**\n- What dataset did you choose and why? 【I used Indego Bike Share Station data from OpenDataPhilly to evaluate spatial equity in bicycle access.】\n- What is the data source and date?  【OpenDataPhilly (updated 2024)】\n- How many features does it contain?  【282】\n- What CRS is it in? Did you need to transform it?  【WGS 84 EPSG: 4326, so i transformed it to match the Philadelphia census tracts to EPSG: 4269】\n\n---\n\n2. **Pose a research question**\n\nWrite a clear research statement that your analysis will answer.\n【This analysis investigates whether low-income neighborhoods in Philadelphia—defined as census tracts with median household income below 80% of the citywide median—have lower accessibility to Indego bike share stations.\nAccessibility is measured by both:\n(1) the number of bike share stations within each census tract,\n(2) the distance from the tract centroid to the nearest station.\nThe goal is to evaluate equity in access to sustainable transportation infrastructure.】\n\n**Examples:**\n- \"Do vulnerable tracts have adequate public transit access to hospitals?\"\n- \"Are EMS stations appropriately located near vulnerable populations?\"\n- \"Do areas with low vehicle access have worse hospital access?\"\n\n---\n\n3. **Conduct spatial analysis**\n\nUse at least TWO spatial operations to answer your research question.\n\n**Required operations (choose 2+):**\n- Buffers\n- Spatial joins\n- Spatial filtering with predicates\n- Distance calculations\n- Intersections or unions\n- Point-in-polygon aggregation\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your spatial analysis\ntract_bikes <- st_join(philly_tracts, bike_stations) %>%\n  group_by(GEOID) %>%\n  summarise(\n    num_stations = n()\n  )\n\ntract_centroids <- st_centroid(philly_tracts)\ndist_matrix <- st_distance(tract_centroids, bike_stations)\ntract_centroids$nearest_station_dist_m <- apply(dist_matrix, 1, min)\ntract_centroids <- tract_centroids %>%\n  mutate(nearest_station_dist_miles = as.numeric(nearest_station_dist_m) / 1609.34)\n\nphilly_tracts <- philly_tracts %>%\n  left_join(st_drop_geometry(tract_centroids)[, c(\"GEOID\", \"nearest_station_dist_miles\")], by = \"GEOID\")\n\nsummary(philly_tracts$nearest_station_dist_miles)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. \n 0.01892  0.16280  0.66885  1.95190  2.91281 11.10948 \n```\n\n\n:::\n\n```{.r .cell-code}\nphl_income <- get_acs(\n  geography = \"tract\",\n  variables = \"B19013_001\",     \n  state = \"PA\",\n  county = \"Philadelphia\",\n  year = 2022,\n  geometry = FALSE,             \n  cache_table = TRUE\n) %>%\n  select(GEOID, med_hh_inc = estimate)\n\nphilly_tracts <- philly_tracts %>%\n  left_join(phl_income, by = \"GEOID\")\ncity_median_income <- median(philly_tracts$med_hh_inc, na.rm = TRUE)\nlow_income_threshold <- 0.8 * city_median_income\nphilly_tracts <- philly_tracts %>%\n  mutate(\n    low_income = med_hh_inc < low_income_threshold\n  )\n\naccess_by_income <- philly_tracts %>%\n  group_by(low_income) %>%\n  summarise(\n    tracts = n(),\n    mean_distance = mean(nearest_station_dist_miles, na.rm = TRUE),\n    median_distance = median(nearest_station_dist_miles, na.rm = TRUE)\n  )\naccess_by_income\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 3 features and 4 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 476067.8 ymin: 4413023 xmax: 503769.6 ymax: 4443073\nProjected CRS: NAD83 / UTM zone 18N\n# A tibble: 3 × 5\n  low_income tracts mean_distance median_distance                       geometry\n  <lgl>       <int>         <dbl>           <dbl>             <MULTIPOLYGON [m]>\n1 FALSE         245          2.46           0.939 (((478150.4 4416645, 478520.2…\n2 TRUE          138          1.11           0.440 (((479066.6 4418402, 478949.8…\n3 NA             25          1.61           0.799 (((480333.3 4414114, 479979.6…\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(philly_tracts, aes(x = low_income, y = nearest_station_dist_miles, fill = low_income)) +\n  geom_boxplot(alpha = 0.7) +\n  scale_fill_manual(values = c(\"FALSE\" = \"#405E70\", \"TRUE\" = \"#8B3A3A\")) +\n  scale_x_discrete(labels = c(\"FALSE\" = \"Non-low-income\", \"TRUE\" = \"Low-income\")) +\n  labs(\n    x = NULL,\n    y = \"Distance to nearest Indego station (miles)\",\n    title = \"Bike-share Accessibility by Income Group\",\n    subtitle = \"Low-income tracts are generally farther from bike share stations\"\n  ) +\n  theme_minimal() +\n  theme(\n    legend.position = \"none\",\n    plot.title = element_text(hjust = 0.5),\n    plot.subtitle = element_text(hjust = 0.5)\n  )\n```\n\n::: {.cell-output-display}\n![](Chen_Xiaoqing_Assignment2_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n**Analysis requirements:**\n- Clear code comments explaining each step\n- Appropriate CRS transformations\n- Summary statistics or counts\n- At least one map showing your findings\n- Brief interpretation of results (3-5 sentences)\n\n**Your interpretation:**\n\n[The analysis shows that low-income census tracts in Philadelphia are, on average, located slightly farther from Indego bike share stations compared to non-low-income tracts.\nThe median distance for low-income areas is about 1 mile, while non-low-income tracts have a median distance closer to 0.6 miles. This suggests that while Indego stations are generally well distributed across the city, access remains more limited in some lower-income neighborhoods, particularly toward the northern and western parts of Philadelphia.\nImproving station coverage in these areas could enhance transportation equity and support sustainable mobility goals.]\n\n\n## Finally - A few comments about your incorporation of feedback!\n\n【Based on the feedback from my first submission, I revised my data loading and CRS transformation steps to make them reproducible and consistent. I also verified that all spatial joins and projections used the same coordinate system.】\n\n---\n\n## Submission Requirements\n\n**What to submit:**\n\n1. **Rendered HTML document posted to your course portfolio** with all code, outputs, maps, and text\n   - Use `embed-resources: true` in YAML so it's a single file\n   - All code should run without errors\n   - All maps and charts should display correctly\n\n**File naming:** `LastName_FirstName_Assignment2.html` and `LastName_FirstName_Assignment2.qmd`\n\n---\n\n",
    "supporting": [
      "Chen_Xiaoqing_Assignment2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}